### ISSUE TITLE
Discloud Log

### ISSUE THREAD

**Issue by mapenjj** [DragonJules/ShopBot#1]
I followed all instructions

        2024-02-19T01:05:00.240597441Z  Ready! Logged in as $BlueBillsShop#5897
        2024-02-19T01:05:01.516762700Z  DiscordAPIError[50001]: Missing Access
        2024-02-19T01:05:01.516792017Z      at handleErrors (/home/node/node_modules/@discordjs/rest/dist/index.js:640:13)
        2024-02-19T01:05:01.516797904Z      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        2024-02-19T01:05:01.516802875Z      at async SequentialHandler.runRequest (/home/node/node_modules/@discordjs/rest/dist/index.js:1021:23)
        2024-02-19T01:05:01.516807673Z      at async SequentialHandler.queueRequest (/home/node/node_modules/@discordjs/rest/dist/index.js:862:14)
        2024-02-19T01:05:01.516812765Z      at async REST.request (/home/node/node_modules/@discordjs/rest/dist/index.js:1387:22) {
        2024-02-19T01:05:01.516817485Z    requestBody: {
        2024-02-19T01:05:01.516821898Z      files: undefined,
        2024-02-19T01:05:01.516826356Z      json: [
        2024-02-19T01:05:01.516830723Z        [Object], [Object],
        2024-02-19T01:05:01.516835081Z        [Object], [Object],
        2024-02-19T01:05:01.516839472Z        [Object], [Object],
        2024-02-19T01:05:01.516843833Z        [Object], [Object],
        2024-02-19T01:05:01.516848130Z        [Object], [Object],
        2024-02-19T01:05:01.516852437Z        [Object], [Object],
        2024-02-19T01:05:01.516856735Z        [Object], [Object]
        2024-02-19T01:05:01.516860991Z      ]
        2024-02-19T01:05:01.516865247Z    },
        2024-02-19T01:05:01.516869614Z    rawError: { message: 'Missing Access', code: 50001 },
        2024-02-19T01:05:01.516874290Z    code: 50001,
        2024-02-19T01:05:01.516878661Z    status: 403,
        2024-02-19T01:05:01.516882957Z    method: 'PUT',
        2024-02-19T01:05:01.516887341Z    url: 'https://discord.com/api/v10/applications/1208931001816973462/guilds/1085750580242305175/commands'
        2024-02-19T01:05:01.516892097Z  }

**Comment by DragonJules** [comment]
Hi, I'm sorry the README isn't up to date, try to follow the tutorial on [this repo](https://github.com/DragonJules/MessageCounter), it's up to date !
I think that it might solve the problem.
I'm going to update the README of this project
Sorry for my late answer.

**Comment by DragonJules** [comment]
So the real problem was probably the intents access that must be set up in the Discord Developer portal, which I forgot to mention have to be enabled for the bot to work, really sorry for this.
