### ISSUE TITLE
Error function

### ISSUE THREAD

**Issue by ilijadivi** [DragonJules/ShopBot#2]
![image](https://github.com/DragonJules/ShopBot/assets/74413068/55ec51c6-a1ed-47fb-8c2a-2af9a73ee367)

**Comment by DragonJules** [comment]
Did you fix the problem or should I look at it ?

**Comment by P3nguinMinecraft** [comment]
I have the same issue

**Comment by P3nguinMinecraft** [comment]
`TypeError: Cannot read properties of null (reading 'name')
    at Object.execute (/Users/apple2020/Desktop/EconomyBot/events/interactionCreate.js:741:101)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
node:events:497
      throw er; // Unhandled 'error' event
      ^

Error [InteractionAlreadyReplied]: The reply to this interaction has already been sent or deferred.
    at ChatInputCommandInteraction.reply (/Users/apple2020/Desktop/EconomyBot/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:104:46)
    at Object.execute (/Users/apple2020/Desktop/EconomyBot/events/interactionCreate.js:744:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
Emitted 'error' event on Client instance at:
    at emitUnhandledRejectionOrErr (node:events:402:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:92:21) {
  code: 'InteractionAlreadyReplied'
}`

**Comment by P3nguinMinecraft** [comment]
Temp Fix: 
this might be from the new discord command setup or smth so just make a if statement for it
In events > interactionCreate.js replace line 741 with below:
```
if (interaction.channel) {
                console.log(`${interaction.user.tag} (${interaction.user.id}) in #${interaction.channel.name} (${interaction.channel.id}) triggered an interaction (${interaction.commandName}).`);
            } else {
                console.log(`${interaction.user.tag} (${interaction.user.id}) triggered an interaction (${interaction.commandName}) without channel information.`);
            }
```

**Comment by DragonJules** [comment]
Please update to the newest version of ShopBot, your issue should be solved
