### ISSUE TITLE
error

### ISSUE THREAD

**Issue by SigimotoAytava** [DragonJules/ShopBot#5]
error when using the /add-product command

ReferenceError: productPrice is not defined
    at Object.execute (/home/runner/ShopBot/commands/add-product.js:68:61)
    at Object.execute (/home/runner/ShopBot/events/interactionCreate.js:740:27)
    at Client.<anonymous> (/home/runner/ShopBot/index.js:57:44)
    at Client.emit (node:events:519:28)
    at InteractionCreateAction.handle (/home/runner/ShopBot/node_modules/discord.js/src/client/actions/InteractionCreate.js:97:12)
    at module.exports [as INTERACTION_CREATE] (/home/runner/ShopBot/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/home/runner/ShopBot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:355:31)
    at WebSocketManager.<anonymous> (/home/runner/ShopBot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:239:12)
    at WebSocketManager.emit (/home/runner/ShopBot/node_modules/@vladfrangu/async_event_emitter/dist/index.cjs:285:31)
    at WebSocketShard.<anonymous> (/home/runner/ShopBot/node_modules/@discordjs/ws/dist/index.js:1190:51)

**Comment by chethanyadav456** [comment]
This error shows that `productPrice` is not defined but in the remote repo it is defined. https://github.com/DragonJules/ShopBot/blob/3592009db6f7ab87344b630fe2e8551c35418130/commands/add-product.js#L36
It must be you have messed up with the code. 
send your code here.

**Comment by DragonJules** [comment]
Please update to the newest version of ShopBot, your issue should be solved
